# Generated by Django 3.2 on 2021-05-02 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pensamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200, unique=True)),
                ('autor_foto', models.URLField(default='URL da foto')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('pensamentos', markdownx.models.MarkdownxField(default='Pensamentos do Autor')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['autor'],
            },
        ),
    ]
