# Generated by Django 3.2 on 2021-05-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='icone',
            field=models.URLField(default='URL do ícone'),
        ),
    ]
