# Generated by Django 3.2 on 2021-05-01 08:35

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='info',
            field=markdownx.models.MarkdownxField(default='Informação sobre o curso'),
        ),
    ]
