# Generated by Django 3.2 on 2021-05-01 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('autor', models.CharField(max_length=200, unique=True)),
                ('capa', models.URLField(default='URL do ícone')),
                ('ano_lancamento', models.DateField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('descricao', markdownx.models.MarkdownxField(default='Descrição do livro')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ano_lancamento'],
            },
        ),
    ]
